export { default as createTemplate } from './post.ts'
export { default as createTemplateFromForm } from './createFromForm.ts'
export { default as createFormFromTemplate } from './duplicateToForm.ts'
export { default as getTemplates } from './get.ts'
export { default as getSharedTemplates } from './getShared.ts'
export { default as getTemplate } from './getById.ts'
export { default as updateTemplate } from './put.ts'
export { default as deleteTemplate } from './delete.ts'
